# Generated by Django 5.0b1 on 2023-11-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=40)),
                ('text2', models.CharField(max_length=40)),
                ('image', models.ImageField(default='', upload_to='uploads/sliders/')),
            ],
        ),
    ]
